site_name: "Bento Documentation -- Dev"
site_dir: "build"

site_url: https://bento-platform.github.io/bento-docs/
repo_url: https://github.com/bento-platform/bento-docs

theme:
  name: "material"

plugins:
  - mike:
      alias_type: symlink
      redirect_template: null
      deploy_prefix: ""
      canonical_version: null
      version_selector: true
      css_dir: css
      javascript_dir: js
