name: Docs CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

## TODO: Add linting for md
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false

      - name: Install dependencies
        run: poetry install --no-interaction --no-ansi --no-root

      - name: Build docs
        run: mkdocs build --strict
