name: Docs CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

## TODO: Add linting for md
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: uv sync --frozen

      - name: Build docs
        run: uv run mkdocs build --strict
