name: 📚 Deploy MkDocs via mike

on:
  release:
    types:
      - published

permissions:
  contents: write
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true
          persist-credentials: true

      - run: git fetch origin gh-pages:gh-pages

      - name: Configure Git author
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false

      - name: Install dependencies
        run: poetry install --no-interaction --no-ansi --no-root

      - name: Deploy documentation
        run: |
          TAG="${{ github.event.release.tag_name }}"
          poetry run mike deploy "$TAG" latest --push
